apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:7eca3d85a6c23309d0da14aca67543a21a81681a
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"

