apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:32a93fd74fafdf972f838b8e866230fc33b37f96
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"

