apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              cpu: "100m"     # Minimum CPU required (100 millicores)
              memory: "128Mi" # Minimum memory required
            limits:
              cpu: "500m"     # Maximum CPU allowed
              memory: "256Mi" # Maximum memory allowed
