apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"

