name: Build and Push Docker Image to ECR

on:
  push:
    branches: [main]
permissions:
  contents: write  # Grants write access to repository content

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your desired region

      # Build Docker image with commit SHA as tag
      - name: Build Docker image
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          docker build -t app:${COMMIT_SHA} .

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533267303892.dkr.ecr.ap-south-1.amazonaws.com

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          docker tag app:${COMMIT_SHA} 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:${COMMIT_SHA}
          docker push 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:${COMMIT_SHA}

      # Update the image tag in k8s/deployment.yaml
      - name: Update Kubernetes deployment file
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          sed -i "s|image: .*/git:.*|image: 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:${COMMIT_SHA}|" k8s/deployment.yaml

      # Commit and push changes to GitHub
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${COMMIT_SHA}"
          git push origin main
