name: Build and Push Docker Image to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your desired region

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest  # Commit hash as the image tag
          docker build -t app:$IMAGE_TAG .

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 533267303892.dkr.ecr.ap-south-1.amazonaws.com

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
           docker tag app:latest 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:latest
           docker push 533267303892.dkr.ecr.ap-south-1.amazonaws.com/git:latest
          


    
