name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Debugging AWS Region
    - name: Debug AWS Region
      run: echo "AWS Region is: ${{ secrets.AWS_REGION }}"

    # Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Ensure secrets are being passed correctly

    # Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA}  # Commit hash as the image tag
        docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    # Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

    # Update Kubernetes manifest with the commit hash
    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image:.*|image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${GITHUB_SHA}|" k8s/deployment.yaml
        git config --global user.email "youremail@example.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Update image tag to ${GITHUB_SHA}"
        git push
