name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

    # Run unit tests (assuming using a Node.js or similar setup)
    # - name: Run unit tests
    #   run: |
    #     # Install dependencies (example for Node.js)
    #     npm install
    #     # Run tests
    #     npm test

    # Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA}  # Commit hash as the image tag
        docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1| docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

    # Push the Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

    # Update Kubernetes manifest with the commit hash
    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image:.*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${GITHUB_SHA}|" k8s/deployment.yaml
        git config --global user.email "ayan.butt@antino.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Update image tag to ${GITHUB_SHA}"
        git push
